name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOCKEN }}

          # Options
          user: jtfoss
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Manila
          plugin_achievements: yes
          plugin_isocalendar: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B
          plugin_languages: yes
          plugin_languages_sections: recently-used
          plugin_languages_recent_days: 7
    
